### ISSUE TITLE
Wrong image in methrix_report: Chromosome-wise depth of coverage

### ISSUE THREAD

**Issue by ClarissaFeuersteinAkgoz** [CompEpigen/methrix#12]
In the methrix_report in the image "Chromosome-wise depth of coverage, MEDIAN" it shows instead of median covarage, median chromosome-wise methylation.

**Comment by PoisonAlien** [comment]
Thanks @ClarissaFeuersteinAkgoz 
Try again from GitHub, and it should be fine.
