### ISSUE TITLE
Error in methrix report with subsetted methrix object

### ISSUE THREAD

**Issue by ClarissaFeuersteinAkgoz** [CompEpigen/methrix#13]
methrix_report(m10masked, "/C010-projects/Pathway_27/SGBS_hydroxymethylation/WGoxBS/QC/methrix_reports_filtered2", recal_stats=T)

error message only occures if recal_stats=T: 

Step 1 of 5: Methylation/Coverage per chromosome
Error in merge.data.table(meth_stat, cov_stat, by = c("chr", "Sample_Name")) : 
  Elements listed in `by` must be valid column names in x and y
In addition: Warning message:
In merge.data.table(meth_stat, cov_stat, by = c("chr", "Sample_Name")) :
  You are trying to join data.tables where 'x' and 'y' arguments are 0 columns data.table.

**Comment by PoisonAlien** [comment]
It seems to work for me.

```r
> x = subset_methrix(m = methrix_data, contigs = 'chr21')
> x
An object of class methrix
   n_CpGs: 540
n_samples: 4
    is_h5: FALSE
Reference: hg19
> methrix::methrix_report(meth = x, output_dir = "./test4/", recal_stats = TRUE)
```

Can you post your complete commands (subletting + report)?
