### ISSUE TITLE
Suggestions for example dataset

### ISSUE THREAD

**Issue by PoisonAlien** [CompEpigen/methrix#2]
Hello @tkik @MaxSchoenung @HeyLifeHD @lutsik ,

As a part of the package it would be nicer to have an example `data` for testing/demonstration. Bsseq has `BS.chr22` which can be loaded with the command `data(BS.chr22)`. In methrix I included a part of single cell dataset from bsmap protocol - `data(mm9_bsmap)`. However @tkik suggested that this dataset is quite "boring" and we should use something more robust - and I agree. 

Two options:

1. We convert the dataset bundled with `bsseq` to `methrix` object and use it.
2. We make our own custom dataset from well studied in-house data. 

If you opt for `2`, we should make sure that we have at-lease two samples while keeping the object size small. For example, bsseq data is quite small (3.8MB) with ~50K loci and 2 samples. Bioconductor has a package size limit of [5 MB](http://master.bioconductor.org/packages/devel/bioc/vignettes/BiocCheck/inst/doc/BiocCheck.html#package-and-file-size-check) and the core team is quite strict in this regard.

```r
> data(BS.chr22)
> BS.chr22
An object of type 'BSseq' with
  494728 methylation loci
  2 samples
has not been smoothed
All assays are in-memory
> print(object.size(x = BS.chr22), units = "MB")
3.8 Mb
```
Suggestions welcome, and please post here if you have an example set in mind.

**Comment by MaxSchoenung** [comment]
I am currently trying to generate some methrix “vanilla” dataset with hESC TET triple knockout. I will try this today and tell you how it works out tomorrow. If this is fine for you ;)
Maximilian Schönung
Cancer Epigenomics
PhD Student

German Cancer Research Center (DKFZ)
Foundation under Public Law
Im Neuenheimer Feld 280
69120 Heidelberg
Germany
phone: +49 6221 42-4321

m.schoenung@dkfz.de<mailto:m.schoenung@dkfz.de>



On 28. May 2019, at 14:26, Anand Mayakonda <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello @tkik<https://github.com/tkik> @MaxSchoenung<https://github.com/MaxSchoenung> @HeyLifeHD<https://github.com/HeyLifeHD> @lutsik<https://github.com/lutsik> ,

As a part of the package it would be nicer to have an example data for testing/demonstration. Bsseq has BS.chr22 which can be loaded with the command data(BS.chr22). In methrix I included a part of single cell dataset from bsmap protocol - data(mm9_bsmap). However @tkik<https://github.com/tkik> suggested that this dataset is quite "boring" and we should use something more robust - and I agree.

Two options:

  1.  We convert the dataset bundled with bsseq to methrix object and use it.
  2.  We make our own custom dataset from well studied in-house data.

If you opt for 2, we should make sure that we have at-lease two samples while keeping the object size small. For example, bsseq data is quite small (3.8MB) with ~50K loci and 2 samples. Bioconductor has a package size limit of 5 MB<http://master.bioconductor.org/packages/devel/bioc/vignettes/BiocCheck/inst/doc/BiocCheck.html#package-and-file-size-check> and the core team is quite strict in this regard.

> data(BS.chr22)
> BS.chr22
An object of type 'BSseq' with
  494728 methylation loci
  2 samples
has not been smoothed
All assays are in-memory
> print(object.size(x = BS.chr22), units = "MB")
3.8 Mb

Suggestions welcome, and please post here if you have an example set in mind.

**Comment by PoisonAlien** [comment]
Yup! Sounds good to me :)
