### ISSUE TITLE
Track annotation is missing when bedGraphs are exported 

### ISSUE THREAD

**Issue by lutsik** [CompEpigen/methrix#23]
To simplify the import of bedGraphs into UCSC Genome Browser it would be great to have the usual track lines (name, etc).

**Comment by PoisonAlien** [comment]
Is it for `write_bedgraphs()` function?

**Comment by lutsik** [comment]
yes

**Comment by PoisonAlien** [comment]
Oh btw this has already been added by @ClarissaFeuersteinAkgoz in PR #18 
Closing this issue.
