### ISSUE TITLE
Bug when exporting bsseq objects from methrix objects created using Methyldackel pipeline

### ISSUE THREAD

**Issue by Christian-Heyer** [CompEpigen/methrix#26]
I've been having a great time using methrix over the past weeks. Thanks for creating such a nice package.

I've run into a bug when reading BedGraph files from Methyldackel using the `pipeline = "MethyDackel` preset and transforming the methrix file into a bsseq object using methrix2bsseq.

The resulting bsseq from methrix2bsseq will have non-integer M-Coverage values when retrieving them using:
```r
meth <-  methrix::read_bedgraphs(n_threads = threads,
                                            files = bedgraph_fps,
                                            pipeline = "Methyldackel"
                                            ref_cpgs = mm10_cpgs,
                                            coldata = meta_data)
bsseq_obj <- methrix::methrix2bsseq(meth)                                
bsseq::getCoverage(bsseq_obj, type = M)
```

I've had a look at the code for `methrix2bsseq` and I think I've found the cause.

When using `pipeline = "MethyDackel`, `read_bedgraph` uses the Methyldackel calculated beta values, however these are rounded to the 2nd decimal place.
Example(4th column):
```
track type="bedGraph" description="SRR1182519.sorted CpG methylation levels"
1	25114	25115	66	2	1
1	25115	25116	100	3	0
```

methrix2bsseq calculates the M-Matrix of methylated reads by multiplying with the coverage, however using these rounded beta values will cause non-integer values to be inserted in the M-Coverage Matrix. 

My workaround for now is setting the read_bedgraph fields manually since then methrix calculates exact beta values itself.
Then everything works out

```r
methrix::read_bedgraphs(n_threads = threads,
                                           files = smoothed_bsseq_files,
                                           chr_idx = 1, start_idx = 2, end_idx = 3, M_idx =5, U_idx = 6,
                                           ref_cpgs = mm10_cpgs,
                                           coldata = meta_data,
                                            
  )
```

Maybe it would make sense having having methrix calculate the Beta values when reading from Methyldackel bedgraphs?

**Comment by PoisonAlien** [comment]
Hi Christian,

Thanks for using `methrix` and it's nice to know that you find it useful.

Regarding the issue, if it is the case then your workaround should be enough. I will change the default configuration for `Methyldackel` to calculate the beta values. I will also check if other presets are doing the same. 
Thanks for letting us know.
