### ISSUE TITLE
Error using HDF5 backend

### ISSUE THREAD

**Issue by pangjli** [CompEpigen/methrix#27]
Hi, 

I used HDF5 backend due to memory issues. I firstly tried to save a RDS file of the output from methrix::read_bedgraphs, but it gives me error that name = '/private/var/folders/0r/35wl9njn767_c2md3zy0h61w0000gn/T/Rtmpp14UbV/M_sink_1.h5', errno = 2, error message = 'No such file or directory'. I checked that there is the file named M_sink_1.h5 in the directory so I don't know what happened here. Also, I tried to remove the h5 file and rerun the code, it gives error that Error in DelayedArray::write_block(block = as.matrix(b$bdg[, .(beta)]),  : 
  unused argument (sink = M_sink). Could you help me? :)

Thanks

**Comment by tkik** [comment]
Hi, 

Could you try running the read_bedgraphs function with the h5temp argument set to a different folder? Maybe it has something to do with accessing that folder. If it still doesn't work, please give me some additional detail about the system you are using and I will look into it.

**Comment by pangjli** [comment]
Hi, 

The same error occurred again and it looks like this. (reset both h5_dir and h5temp gives that error)

<img width="954" alt="Screen Shot 2021-04-24 at 11 57 17 AM" src="https://user-images.githubusercontent.com/74547628/115946570-b32d5480-a4f4-11eb-845b-5910322dca95.png">

I'm using R 3.6.3 from OS darwin15.6.0.

Thanks a lot again!

**Comment by tkik** [comment]
Hi, 

The reason might be the old R version. We have seen similar behavior before when the versions of DelayedArray and methrix packages are not "synchronized", e.g. you have a newer version of methrix with an older version of DelayedArray or vica versa. The DelayedArray package changed between 3.6 and 4.0 and we followed this change with methrix, but if one of them is an older version and the other one is new, something like this can happen. Is it possible for you to update R and re-install methrix, DelayedArray and SummarizedExperiment? If not, could you please post your sessionInfo()? I can then try to figure out how to downgrade one of the packages to make it work.

**Comment by pangjli** [comment]
Hello! I guess the reason does lie in the R version. I updated my R version to 4.0 and it finally worked!! 👍 
Many thanks!!!
Btw, the package is really convenient for some methylation analysis!
Wish you have a nice weekend :)
