### ISSUE TITLE
Typo in the documentation

### ISSUE THREAD

**Issue by ClarissaFeuerstein** [CompEpigen/methrix#5]
in documenatation: at STEP2

meth = methrix::read_bedgraphs(files = bdg_files[1:3], pipeline = "MethylcTools", **collapse_starnds** = TRUE, vect_batch_size = 3, ref_build = "Hs37d5", ref_cpgs = hs37d5_cpgs)

collapse_starnds  --> collapse_strands

**Comment by tkik** [comment]
Corrected it in [0e0371c](https://github.com/CompEpigen/methrix/commit/0e0371cc6e9fdfb950cf96507a5915c85e5ea846)
