### ISSUE TITLE
Typos in diagnostic messages when extracting CpGs

### ISSUE THREAD

**Issue by lutsik** [CompEpigen/methrix#6]
Could not find BSgenome BSgenome.Hsapiens.UCSC.mm10
Found following BSgenome __installtions__. Provide the correct 'pkgname'

**Comment by lutsik** [comment]
And also in the saving routine:

> save_HDF5_methrix(meth, dir=OUT_DIR)
Error in save_HDF5_methrix(meth, dir = OUT_DIR) :
  The object is not a mthrix object or not in an HDF5 format.

**Comment by lutsik** [comment]
and further typos:

Step 1 of 5: Methylation/Coverage per chromosome
Step 2 of 5: Global methylation/Coverage per sample
Step 3 of 5: Reference CpGs __coevered__ per chromosome
Step 4 of 5: Common reference CpGs covered across all samples

**Comment by tkik** [comment]
Edited in https://github.com/CompEpigen/methrix/commit/9e8a2f425cab11baa39a1f031a948ba2b338a177 
Thanks!
