### ISSUE TITLE
Error while masking CpGs based on coverage

### ISSUE THREAD

**Issue by lutsik** [CompEpigen/methrix#7]
> meth <- methrix::mask_methrix(m = meth, low_count=5, high_quantile = 0.99)
-Masked 5,498,862 CpGs due to low coverage.
Error in `[<-`(`*tmp*`, row_idx, value = NA) :
  linear subassignment to a DelayedArray object 'x' (i.e. 'x[i] <-
  value') is only supported when the subscript 'i' is a logical
  DelayedArray object of the same dimensions as 'x' and 'value' an
  ordinary vector of length 1)
> traceback()
4: stop(wmsg(.linear_subassign_error_msg))
3: `[<-`(`*tmp*`, row_idx, value = NA)
2: `[<-`(`*tmp*`, row_idx, value = NA)
1: methrix::mask_methrix(m = meth, low_count = 5, high_quantile = 0.99)
>
>
>

**Comment by tkik** [comment]
Fixed in https://github.com/CompEpigen/methrix/commit/4222e1c67b9402981e497d22e649e675d0943e8a.
