### ISSUE TITLE
Error while removing uncovered CpGs

### ISSUE THREAD

**Issue by lutsik** [CompEpigen/methrix#8]
>
>
>
> meth <- methrix::remove_uncovered(m = meth)
Error in as.vector(x, "list") :
  cannot coerce type 'closure' to vector of type 'list'
> traceback)(
Error: unexpected ')' in "traceback)"
> traceback()
No traceback available
>
>
>

**Comment by tkik** [comment]
Solved in https://github.com/CompEpigen/methrix/commit/32723217fda38a7f75f636876fb0a8c43a8fcc3f.
