### ISSUE TITLE
Error while summarising regions 

### ISSUE THREAD

**Issue by lutsik** [CompEpigen/methrix#9]
>
> summary_data_tables<-list()
> for(i in seq(granges_list)){
+     summary_data_tables[[i]]<-get_region_summary(m = meth, regions = granges_list[[i]], type = "M", how = "mean")
+ }
-Checking for overlaps..
-Summarizing by average
Error in `[.data.table`(dat, , lapply(.SD, mean, na.rm = na_rm), by = yid,  :
  Some items of .SDcols are not column names: [cells01-rep1, cells01-rep2, cells01-rep3, cells02-rep1, cells02-rep2, cells02-rep3, cells03-rep1, cells03-rep2, cells03-rep3, cells04-rep1, ...]

**Comment by PoisonAlien** [comment]
Can you provide a reproducible example? It appears to be an issue with `-` in column names. `SummarizedExperiment` has issues with symbols inside sample names and @tkik seems to have taken care of it a while ago.

**Comment by lutsik** [comment]
I can only save the object and give you the script. What is a while ago? I loaded the object less than two weeks ago.

**Comment by tkik** [comment]
It was months ago. Could you send me the script?

**Comment by tkik** [comment]
Ok, I see the problem. To add sample annotation, you have to use the read_bedraphs function's coldata argument. You added the sample info later: meth@colData<-DataFrame(sample_info), therefore it didn't get "connected" with the other datasets in the methrix object. If you use it in the function, it will take care of the non-valid sample names as well. Most probably this causes your other problems too. 
I am sending you back the modified script.

**Comment by lutsik** [comment]
Thanks! I was looking for that option, but failed to find it somehow. I will try again and close the issue accordingly.
